name: helloworld
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  image_picker: ^1.1.2
  provider: ^6.1.5
  # firebase_auth: ^3.11.2
  # firebase_core: ^1.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/computer.jpg
    - assets/img/headset.jpg
    - assets/img/radio.jpg
    - assets/img/smartphone.jpg
    - assets/img/dark-pola.png
    - assets/img/dark-pola.jpg
